apiVersion: v1
kind: ConfigMap
metadata:
  name: xray-config
data:
  config.json: |
    {
      "log": {
          "loglevel": "warning"
      },
      "inbounds": [
          {
              "port": 443,                                      \\ CHANGE IF NEEDED, RECOMMEND TO LEAVE 443
              "listen": "0.0.0.0",                              \\ CHANGE IF NEEDED, RECOMMEND TO NOT
              "protocol": "vless",
              "settings": {
                  "clients": [
                      {
                          "id": "{{SERVERID}}",                 \\ CREATE YOUR ID, LOOK FOR GENERATION ../scripts
                          "flow": "xtls-rprx-vision"            \\ DO NOT CHANGE
                      }
                  ],
                  "decryption": "none"
              },
              "streamSettings": {
                  "network": "tcp",
                  "security": "reality",
                  "realitySettings": {
                      "dest": "{{WEBSITE}}:443",                \\ CHANGE TO SERVER YOURE MASQUERADING FOR EXAMPLE www.google.com or google.com
                      "serverNames": [
                          "{{WEBSITE}}",                        \\ CHANGE TO SERVER YOURE MASQUARADING FOR EXAMPLE google.com
                          "www.{{WEBSITE}}"                     \\ CHANGE TO SERVER YOURE MASQUARADING FOR EXAMPLE www.google.com
                      ],
                      "privateKey": "{{PRIVKEY}}",           \\ CREATE YOUR PUB&PRIV PAIR, PUT HERE PRIVKEY, SCRIPT FOR GENERATE IN ../scripts FOLDER
                      "shortIds": [
                          "{{SHORTID1}}",
                          "{{SHORTID2}}",                       \\ CREATE ShortID FOR CLIENT. YOU CAN LEAVE ONLY 1 ID OR CREATE AS MANY AS YOU WANT. GENERATE VIA openssl rand -hex 6
                      ],
                      "acceptProxyProtocol": false
                  }
              },
              "sniffing": {
                  "enabled": true,
                  "destOverride": [
                      "http",
                      "tls"
                  ]
              }
          }
      ],
      "outbounds": [
          {
              "protocol": "freedom",
              "tag": "direct"
          }
      ]
    }
